jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_USER}"
          password: "${JENKINS_PASS}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      pipelineJob('docker-test') {
        definition {
          cps {
            script('''
              pipeline {
                agent any
                stages {
                  stage('test docker') {
                    steps {
                      sh 'docker ps'
                    }
                  }
                }
              }
            ''')
            sandbox()
          }
        }
      }

  - script: >
      pipelineJob('jenkins-env-automation') {
        description('This job sets up the Jenkins environment using jenkins_automation repo for code and jenkins_configs repo for Jenkinsfile.')
        definition {
          cpsScm {
            scm {
              // Verwende Multiple SCMs, um mehrere Repositories zu klonen
              multibranch {
                sources {
                  git {
                    remote {
                      url('https://github.com/cqNikolaus/jenkins_automation.git')
                    }
                    branch('main')
                  }
                  git {
                    remote {
                      url('https://github.com/cqNikolaus/jenkins_configs.git')
                    }
                    branch('bootstrap')
                  }
                }
              }
            }
            scriptPath('jenkins_configs/Jenkinsfile')
          }
        }
      }

  - script: >
      pipelineJob('jenkins-setup') {
        description('This job sets up Jenkins using the Jenkinsfile_setup.')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/cqNikolaus/jenkins_automation.git')
                }
                branch('main')
              }
            }
            scriptPath('jenkins_configs/Jenkinsfile_setup')
          }
        }
      }

  - script: >
      pipelineJob('BuildImage') {
        definition {
          cps {
            script('''
              node() {
                git branch: 'bootstrap', url: 'https://github.com/cqNikolaus/jenkins_configs.git'
                dir('jenkins_automation') {
                  git branch: 'main', url: 'https://github.com/cqNikolaus/jenkins_automation.git'
                }
                sh "ls -lart"
                sh "docker build --no-cache -t python-build ."
                }
            ''')
            sandbox()
          }
        }
      }

unclassified:
  location:
    url: "${DOMAIN}"

appearance:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true
