jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_USER}"
          password: "${JENKINS_PASS}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      pipelineJob('docker-test') {
        definition {
          cps {
            script('''
              pipeline {
                agent any
                stages {
                  stage('test docker') {
                    steps {
                      sh 'docker ps'
                    }
                  }
                }
              }
            ''')
            sandbox()
          }
        }
      }

  - script: >
      pipelineJob('jenkins-env-automation') {
        description('This job sets up the Jenkins environment and runs tests using the Jenkinsfile.')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/cqNikolaus/jenkins_automation.git')
                }
                branch('main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

  - script: >
      pipelineJob('jenkins-setup') {
        description('This job sets up Jenkins using the Jenkinsfile_setup.')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/cqNikolaus/jenkins_automation.git')
                }
                branch('main')
              }
            }
            scriptPath('Jenkinsfile_setup')
          }
        }
      }

  - script: >
      pipelineJob('BuildImage') {
        definition {
          cps {
            script('''
              node() {
                checkout scm
                sh "ls -lart"
                sh "docker build -f jenkins_config/Dockerfile --no-cache -t python-build ."
              }
            ''')
            sandbox()
          }
        }
      }

unclassified:
  location:
    url: "${DOMAIN}"

appearance:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true
